// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { NgClass } from '@angular/common';
import { Component, computed, DestroyRef, inject, input, OnInit, signal, viewChild } from '@angular/core';
import { takeUntilDestroyed, toObservable, toSignal } from '@angular/core/rxjs-interop';
import { FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ButtonComponent } from '@components/button/button.component';
import { CalendarComponent } from '@components/calendar/calendar.component';
import { FeatureToggleComponent } from '@components/feature-toggle/feature-toggle.component';
import { InputNumberComponent } from '@components/input-number/input-number.component';
import { InputTextComponent } from '@components/input-text/input-text.component';
import { SelectComponent } from '@components/select/select.component';
import { TextareaComponent } from '@components/textarea/textarea.component';
import { TimePickerComponent } from '@components/time-picker/time-picker.component';
import { UserSearchComponent } from '@components/user-search/user-search.component';
import { GenerateAgendaRequest, MeetingTemplate } from '@lfx-one/shared';
import { MEETING_DURATION_OPTIONS, RECURRING_MEETING_FEATURE, TIMEZONES, YOUTUBE_MAX_MEETING_TITLE_LENGTH } from '@lfx-one/shared/constants';
import { UserSearchResult } from '@lfx-one/shared/interfaces';
import { getTimezoneUtcOffsetString, getWeekOfMonth } from '@lfx-one/shared/utils';
import { MeetingService } from '@services/meeting.service';
import { ProjectContextService } from '@services/project-context.service';
import { MessageService } from 'primeng/api';
import { TooltipModule } from 'primeng/tooltip';
import { finalize, map, merge, of, startWith, switchMap, take, tap } from 'rxjs';

import { AgendaTemplateSelectorComponent } from '../agenda-template-selector/agenda-template-selector.component';
import { MeetingRecurrencePatternComponent } from '../meeting-recurrence-pattern/meeting-recurrence-pattern.component';

@Component({
  selector: 'lfx-meeting-details',
  imports: [
    NgClass,
    ReactiveFormsModule,
    ButtonComponent,
    CalendarComponent,
    FeatureToggleComponent,
    InputNumberComponent,
    InputTextComponent,
    SelectComponent,
    TextareaComponent,
    TimePickerComponent,
    UserSearchComponent,
    TooltipModule,
    AgendaTemplateSelectorComponent,
    MeetingRecurrencePatternComponent,
  ],
  templateUrl: './meeting-details.component.html',
})
export class MeetingDetailsComponent implements OnInit {
  private readonly meetingService = inject(MeetingService);
  private readonly messageService = inject(MessageService);
  private readonly projectContextService = inject(ProjectContextService);

  // Form group input from parent
  public readonly form = input.required<FormGroup>();

  // Dependency injection
  private readonly destroyRef = inject(DestroyRef);

  // AI Agenda Helper signals
  public readonly showAiHelper = signal<boolean>(false);
  public readonly isGeneratingAgenda = signal<boolean>(false);

  // Template selector signals
  public readonly showTemplateSelector = signal<boolean>(false);
  public readonly selectedTemplateId = signal<string | null>(null);

  // Custom recurrence pattern signals
  public readonly showCustomRecurrence = signal<boolean>(false);

  // Auto-title generation signals
  public readonly titleWasAutoGenerated = signal<boolean>(false);

  // Owner (organizer) picker signals
  public readonly ownerManualEntry = signal<boolean>(false);

  // The single organizer picker instance — needed to reset its internal input text on Clear
  // (the box seeds itself from ownerEmail on init, and nulling the bound controls doesn't empty it).
  private readonly ownerSearch = viewChild(UserSearchComponent);

  public readonly youtubeTitleLimit = YOUTUBE_MAX_MEETING_TITLE_LENGTH;
  public readonly youtubeAmberThreshold = Math.floor(YOUTUBE_MAX_MEETING_TITLE_LENGTH * 0.9);
  public readonly titleLength = toSignal(
    toObservable(this.form).pipe(
      switchMap((f) => {
        const ctrl = f.get('title');
        if (!ctrl) return of(0);
        return ctrl.valueChanges.pipe(
          startWith(ctrl.value as string | null),
          map((v: string | null) => v?.length ?? 0)
        );
      })
    ),
    { initialValue: 0 }
  );

  // Current organizer (owner) selection shown under the search box — lfx-user-search clears its
  // own input after a pick, so this label is the only visible confirmation of the selection.
  public readonly selectedOwnerLabel = toSignal(
    toObservable(this.form).pipe(
      switchMap((f) => {
        const nameCtrl = f.get('ownerName');
        const emailCtrl = f.get('ownerEmail');
        if (!nameCtrl || !emailCtrl) return of('');
        return merge(nameCtrl.valueChanges, emailCtrl.valueChanges).pipe(
          startWith(null),
          map(() => {
            const name = ((nameCtrl.value as string | null) || '').trim();
            const email = ((emailCtrl.value as string | null) || '').trim();
            if (name && email) {
              return `${name} (${email})`;
            }
            return name || email;
          })
        );
      })
    ),
    { initialValue: '' }
  );

  // Duration options from shared constants
  public readonly durationOptions = MEETING_DURATION_OPTIONS;

  // Feature toggle configs
  public readonly recurringFeature = RECURRING_MEETING_FEATURE;

  // Recurrence options (dynamically updated based on selected date)
  public recurrenceOptions = signal<{ label: string; value: string }[]>([]);

  // Timezone options — rebuilt whenever the meeting date changes so DST offsets are correct
  public readonly timezoneOptions = signal<{ label: string; value: string }[]>(this.buildTimezoneOptions(new Date()));

  // Minimum date (yesterday)
  public readonly minDate = computed(() => {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    yesterday.setHours(0, 0, 0, 0);
    return yesterday;
  });

  public ngOnInit(): void {
    // Initialize recurrence and timezone options with current start date
    const initialStartDate = this.form().get('startDate')?.value;
    if (initialStartDate) {
      this.generateRecurrenceOptions(initialStartDate);
      this.timezoneOptions.set(this.buildTimezoneOptions(initialStartDate as Date));
    } else {
      this.recurrenceOptions.set([{ label: 'Does not repeat', value: 'none' }]);
    }

    // Add custom duration validator when duration is 'custom'
    this.form()
      .get('duration')
      ?.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((value) => {
        const customDurationControl = this.form().get('customDuration');
        if (value === 'custom') {
          customDurationControl?.setValidators([Validators.required, Validators.min(5), Validators.max(480)]);
        } else {
          customDurationControl?.clearValidators();
        }
        customDurationControl?.updateValueAndValidity();
      });

    // Update recurrence pattern when start date changes
    this.form()
      .get('startDate')
      ?.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((newDate) => {
        this.handleStartDateChange(newDate as Date);
        this.timezoneOptions.set(this.buildTimezoneOptions((newDate as Date) ?? new Date()));
      });

    // Watch for isRecurring changes to reset recurrence
    this.form()
      .get('isRecurring')
      ?.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((isRecurring) => {
        if (!isRecurring) {
          this.form().get('recurrenceType')?.setValue('none');
          this.showCustomRecurrence.set(false);
        } else {
          const recurrenceType = this.form().get('recurrenceType')?.value;
          if (!recurrenceType || recurrenceType === 'none') {
            this.form().get('recurrenceType')?.setValue('weekly');
          }
        }
      });

    // Watch for recurrence value changes to show/hide custom component and set recurrence FormGroup
    this.form()
      .get('recurrenceType')
      ?.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((recurrenceValue) => {
        this.showCustomRecurrence.set(recurrenceValue === 'custom');
        this.updateRecurrenceFormGroup(recurrenceValue);
      });

    // Initialize showCustomRecurrence based on current form value
    const currentRecurrence = this.form().get('recurrenceType')?.value;
    if (currentRecurrence === 'custom') {
      this.showCustomRecurrence.set(true);
    }

    // A hand-edited name/email can no longer be tied to an LFID, so the first actual edit in
    // manual mode drops any username left from a search pick or hydration. Clearing on edit
    // (not on mode switch) keeps an accidental "manual → back to search" round trip a no-op —
    // prepareOwnerData still sees the hydrated owner unchanged and omits the key.
    const ownerNameCtrl = this.form().get('ownerName');
    const ownerEmailCtrl = this.form().get('ownerEmail');
    const ownerUsernameCtrl = this.form().get('ownerUsername');
    if (ownerNameCtrl && ownerEmailCtrl && ownerUsernameCtrl) {
      merge(ownerNameCtrl.valueChanges, ownerEmailCtrl.valueChanges)
        .pipe(takeUntilDestroyed(this.destroyRef))
        .subscribe(() => {
          if (this.ownerManualEntry() && ownerUsernameCtrl.value) {
            ownerUsernameCtrl.setValue(null);
          }
        });
    }
  }

  // Owner picker: lfx-user-search patches ownerEmail/ownerUsername through its control bindings;
  // the display name is composed here instead of binding firstNameControl/lastNameControl, which
  // would clobber each other writing into the single ownerName control.
  public handleOwnerSelection(user: UserSearchResult): void {
    const fullName = [user.first_name, user.last_name].filter(Boolean).join(' ').trim();
    this.form()
      .get('ownerName')
      ?.setValue(fullName || null);
  }

  // The search pool is the indexed meeting-registrant directory, so a user who has never been
  // registered to a meeting the caller can see is unfindable there — manual entry covers them.
  // Any lingering username is dropped on the first manual edit (see the subscription in ngOnInit),
  // not here, so switching modes without editing stays side-effect free.
  public switchToOwnerManualEntry(): void {
    this.ownerManualEntry.set(true);
  }

  public backToOwnerSearch(): void {
    // An invalid manual email would keep gating the step invisibly after the switch — its error
    // message only renders in manual mode, and the remounted search box is a separate control that
    // can't edit ownerEmail. Discard the WHOLE abandoned draft, not just the email: the username is
    // already gone (dropped on the first manual edit), so keeping the name would leave a valid
    // name-only trio that a later save sends as `owner` — replacing the stored organizer's
    // email/username/profile_picture upstream. All-empty controls omit the key instead, exactly
    // like Clear, so the stored owner survives (as the helper text says). A valid draft is kept.
    if (this.form().get('ownerEmail')?.invalid) {
      this.clearOwnerSelection();
    }
    this.ownerManualEntry.set(false);
  }

  // lfx-user-search binds ownerEmail/ownerUsername but not ownerName (composed in
  // handleOwnerSelection), so its clear can't reach the name — sync it on the explicit clear event
  // instead of inferring "cleared" from empty bound controls, which could misread an edit
  // hydration that patches the name before an empty email emits.
  public handleOwnerSearchCleared(): void {
    this.form().get('ownerName')?.setValue(null);
  }

  // Reverting a selection: lfx-user-search empties its own input right after a pick, so PrimeNG's
  // in-field clear icon never shows for a committed selection — this button is the clear
  // affordance instead. Emptying every owner control makes the save omit the `owner` key (create:
  // upstream defaults to the creator; edit: the stored owner is preserved, as the helper text says).
  public clearOwnerSelection(): void {
    const form = this.form();
    form.get('ownerUsername')?.setValue(null);
    form.get('ownerName')?.setValue(null);
    form.get('ownerEmail')?.setValue(null);
    // The search box seeds its own input text from ownerEmail on init; nulling the controls
    // doesn't empty it, so reset the picker itself too (absent in manual mode, where no box shows).
    this.ownerSearch()?.onSearchClear();
  }

  // AI Helper public methods
  public showAiAgendaHelper(): void {
    this.showAiHelper.set(true);
  }

  public hideAiAgendaHelper(): void {
    this.showAiHelper.set(false);
    this.form().get('aiPrompt')?.setValue('');
  }

  public async generateAiAgenda(): Promise<void> {
    const context = this.form().get('aiPrompt')?.value;
    const currentProject = this.projectContextService.activeContext();
    const form = this.form();
    const title = form.get('title')?.value;
    const meetingType = form.get('meeting_type')?.value;

    if (!currentProject || !title || !meetingType || !context) {
      this.messageService.add({
        severity: 'warn',
        summary: 'Missing Information',
        detail: 'Please fill in the meeting title, type, and prompt before generating an agenda.',
      });
      return;
    }

    const request: GenerateAgendaRequest = {
      meetingType,
      title,
      projectName: currentProject.name,
      context,
      maxCharacters: 2000,
    };

    this.isGeneratingAgenda.set(true);

    this.meetingService
      .generateAgenda(request)
      .pipe(
        take(1),
        tap({
          next: (response) => {
            // Set the generated agenda in the form
            this.form().get('description')?.setValue(response.agenda);

            // Set the AI-estimated duration
            this.setEstimatedDuration(response.estimatedDuration);

            this.messageService.add({
              severity: 'success',
              summary: 'Agenda Generated',
              detail: 'AI has successfully generated a meeting agenda.',
            });
          },
          error: (error) => {
            console.error('Failed to generate agenda:', error);
            this.messageService.add({
              severity: 'error',
              summary: 'Generation Failed',
              detail: 'Failed to generate agenda. Please try again.',
            });
          },
          complete: () => {
            this.hideAiAgendaHelper();
          },
        }),
        finalize(() => {
          this.isGeneratingAgenda.set(false);
        })
      )
      .subscribe();
  }

  // Template selector public methods
  public showAgendaTemplateSelector(): void {
    this.showTemplateSelector.set(true);
  }

  public hideAgendaTemplateSelector(): void {
    this.showTemplateSelector.set(false);
    this.selectedTemplateId.set(null);
  }

  public applyTemplate(template: MeetingTemplate): void {
    this.form().get('description')?.setValue(template.content);
    this.selectedTemplateId.set(template.id);

    // Set duration based on template
    this.setEstimatedDuration(template.estimatedDuration);

    this.hideAgendaTemplateSelector();
  }

  private setEstimatedDuration(estimatedDuration: number): void {
    // Check if the estimated duration matches one of our standard options
    const standardDuration = this.durationOptions.find((option) => typeof option.value === 'number' && option.value === estimatedDuration);

    if (standardDuration) {
      // Use standard duration option
      this.form().get('duration')?.setValue(estimatedDuration);
      this.form().get('customDuration')?.setValue(null);
    } else {
      // Use custom duration
      this.form().get('duration')?.setValue('custom');
      this.form().get('customDuration')?.setValue(estimatedDuration);
    }
  }

  private generateRecurrenceOptions(date: Date): void {
    const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    const dayName = dayNames[date.getDay()];

    // Calculate which occurrence of the day in the month (1st, 2nd, 3rd, 4th, or last)
    const { weekOfMonth, isLastWeek } = getWeekOfMonth(date);
    const ordinals = ['', '1st', '2nd', '3rd', '4th'];
    const ordinal = ordinals[weekOfMonth] || `${weekOfMonth}th`;

    const options = [
      { label: 'Does not repeat', value: 'none' },
      { label: 'Daily', value: 'daily' },
      { label: `Weekly on ${dayName}`, value: 'weekly' },
      { label: 'Every weekday', value: 'weekdays' },
    ];

    // If this is the last occurrence, show "Monthly on the last [day]" instead of "Monthly on the Nth [day]"
    if (isLastWeek) {
      options.splice(4, 0, { label: `Monthly on the last ${dayName}`, value: 'monthly_last' });
    } else {
      options.splice(4, 0, { label: `Monthly on the ${ordinal} ${dayName}`, value: 'monthly_nth' });
    }

    // Add custom option at the end
    options.push({ label: 'Custom...', value: 'custom' });

    this.recurrenceOptions.set(options);
  }

  private handleStartDateChange(newDate: Date): void {
    const currentRecurrenceType = this.form().get('recurrenceType')?.value;

    // Always regenerate options for the new date
    this.generateRecurrenceOptions(newDate);

    if (!currentRecurrenceType || currentRecurrenceType === 'none') {
      // No recurrence set, nothing to update
      return;
    }

    // Update recurrence patterns based on type
    switch (currentRecurrenceType) {
      case 'weekly':
        // Update simple weekly pattern to new day
        this.updateSimpleWeeklyPattern(newDate);
        break;

      case 'monthly_nth':
      case 'monthly_last':
        // Update monthly pattern based on new date position
        this.updateMonthlyPattern(newDate, currentRecurrenceType);
        break;
      // Other pattern will be handled by the recurrence pattern component
    }
  }

  private updateSimpleWeeklyPattern(newDate: Date): void {
    const recurrenceFormGroup = this.form().get('recurrence');
    if (recurrenceFormGroup) {
      recurrenceFormGroup.patchValue({
        weekly_days: String(newDate.getDay() + 1), // Convert 0-6 to 1-7
      });
    }
  }

  private updateMonthlyPattern(newDate: Date, recurrenceType: string): void {
    const { weekOfMonth, isLastWeek } = getWeekOfMonth(newDate);
    const recurrenceFormGroup = this.form().get('recurrence');

    if (recurrenceFormGroup) {
      // Update the recurrence type if it changed from nth to last or vice versa
      if ((recurrenceType === 'monthly_nth' && isLastWeek) || (recurrenceType === 'monthly_last' && !isLastWeek)) {
        this.form()
          .get('recurrenceType')
          ?.setValue(isLastWeek ? 'monthly_last' : 'monthly_nth');
      }

      recurrenceFormGroup.patchValue({
        monthly_week: isLastWeek ? -1 : weekOfMonth,
        monthly_week_day: newDate.getDay() + 1, // Convert 0-6 to 1-7
      });
    }
  }

  private updateRecurrenceFormGroup(recurrenceType: string): void {
    const recurrenceFormGroup = this.form().get('recurrence');
    if (!recurrenceFormGroup) return;

    const startDate = this.form().get('startDate')?.value as Date;

    // Reset the recurrence FormGroup
    recurrenceFormGroup.patchValue({
      type: null,
      repeat_interval: 0,
      weekly_days: null,
      monthly_day: null,
      monthly_week: null,
      monthly_week_day: null,
      end_date_time: null,
      end_times: null,
    });

    switch (recurrenceType) {
      case 'none':
        // For none, keep repeat_interval as 0
        break;

      case 'daily':
        recurrenceFormGroup.patchValue({
          type: 1, // Daily
          repeat_interval: 1,
        });
        break;

      case 'weekly':
        recurrenceFormGroup.patchValue({
          type: 2, // Weekly
          repeat_interval: 1,
          weekly_days: String(startDate.getDay() + 1), // Convert 0-6 to 1-7
        });
        break;

      case 'weekdays':
        recurrenceFormGroup.patchValue({
          type: 2, // Weekly
          repeat_interval: 1,
          weekly_days: '2,3,4,5,6', // Monday to Friday
        });
        break;

      case 'monthly_nth':
      case 'monthly_last': {
        const { weekOfMonth, isLastWeek } = getWeekOfMonth(startDate);
        recurrenceFormGroup.patchValue({
          type: 3, // Monthly
          repeat_interval: 1,
          monthly_week: isLastWeek ? -1 : weekOfMonth,
          monthly_week_day: startDate.getDay() + 1, // Convert 0-6 to 1-7
        });
        break;
      }

      case 'custom':
        // For custom, the recurrence pattern component will handle the values
        break;
    }
  }

  private buildTimezoneOptions(date: Date): { label: string; value: string }[] {
    return TIMEZONES.map((tz) => {
      const offset = getTimezoneUtcOffsetString(tz.value, date);
      return {
        label: offset ? `${tz.label} (${offset})` : tz.label,
        value: tz.value,
      };
    });
  }
}
