// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type {
  FilterOption,
  OrgMeeting,
  OrgMeetingAttendanceStatus,
  OrgMeetingRsvpStatus,
  OrgMeetingsTabConfig,
  OrgMeetingsTabId,
  OrgMeetingType,
  OrgMeetingTypeBadge,
  OrgPastMeeting,
} from '../interfaces';

/** Org Meetings page tabs in visible order (`upcoming` is the default). */
export const ORG_MEETINGS_TABS: readonly OrgMeetingsTabConfig[] = [
  { id: 'upcoming', label: 'Upcoming' },
  { id: 'past', label: 'Past' },
] as const;

/** Default tab — URL drops `?tab=` when active to keep deep links clean. */
export const DEFAULT_ORG_MEETINGS_TAB_ID: OrgMeetingsTabId = 'upcoming';

/** Derived from ORG_MEETINGS_TABS; used to validate `?tab=` query-param input. */
export const VALID_ORG_MEETINGS_TAB_IDS: ReadonlySet<OrgMeetingsTabId> = new Set(ORG_MEETINGS_TABS.map((t) => t.id));

/** Default / max page size for the server-paginated Upcoming meetings list. */
export const DEFAULT_MEETINGS_PAGE_SIZE = 10;
export const MAX_MEETINGS_PAGE_SIZE = 100;

/** App-relative base path for the "See Meeting Details" route (see `deriveMeetingDetailsUrl`); resolved to an absolute URL by callers via `toAbsoluteUrl`. */
export const ORG_MEETING_DETAILS_BASE_URL = '/meetings';

/** Valid meeting-type filter values for server-side validation. */
export const VALID_ORG_MEETING_TYPE_VALUES: ReadonlySet<OrgMeetingType> = new Set<OrgMeetingType>(['board', 'marketing', 'technical', 'other']);

/** Label + icon + badge style per meeting type, shared by the upcoming/past meeting-card type badges. */
export const ORG_MEETING_TYPE_LABELS: Record<OrgMeetingType, OrgMeetingTypeBadge> = {
  board: { label: 'Board', icon: 'fa-light fa-people-group', badgeClass: 'border border-blue-400 text-blue-600' },
  marketing: { label: 'Marketing', icon: 'fa-light fa-bullhorn', badgeClass: 'border border-violet-400 text-violet-600' },
  technical: { label: 'Technical', icon: 'fa-light fa-code', badgeClass: 'border border-emerald-400 text-emerald-600' },
  other: { label: 'Other', icon: 'fa-light fa-grid-2', badgeClass: 'bg-gray-100 text-gray-600' },
};

/** RSVP badge label/style per status, for the Org Meetings upcoming invitee list. */
export const ORG_MEETINGS_RSVP_BADGES: Record<Exclude<OrgMeetingRsvpStatus, null>, { label: string; badgeClass: string }> = {
  yes: { label: 'Accepted', badgeClass: 'bg-emerald-50 text-emerald-600' },
  maybe: { label: 'Tentative', badgeClass: 'bg-amber-50 text-amber-600' },
  no: { label: 'Declined', badgeClass: 'bg-red-50 text-red-600' },
};

/** RSVP badge shown when an invitee has not responded. */
export const ORG_MEETINGS_NO_RESPONSE_BADGE = { label: 'No Response', badgeClass: 'bg-gray-100 text-gray-500' };

/** Attendance badge label/style per status, for the Org Meetings past invitee list. */
export const ORG_MEETINGS_ATTENDANCE_BADGES: Record<OrgMeetingAttendanceStatus, { label: string; badgeClass: string }> = {
  attended: { label: 'Attended', badgeClass: 'bg-emerald-50 text-emerald-600' },
  missed: { label: 'Missed', badgeClass: 'bg-red-50 text-red-600' },
  excused: { label: 'Excused', badgeClass: 'bg-amber-50 text-amber-600' },
};

/** Type filter options for the Org Meetings filter bar. */
export const ORG_MEETINGS_TYPE_OPTIONS: FilterOption<OrgMeetingType | null>[] = [
  { label: 'All Types', value: null },
  { label: 'Board', value: 'board' },
  { label: 'Marketing', value: 'marketing' },
  { label: 'Technical', value: 'technical' },
  { label: 'Other', value: 'other' },
];

/**
 * Builds a demo meeting's start/end ISO timestamps relative to the current time, so the
 * Upcoming/Past demo data (and the e2e assertions that depend on it) stay valid indefinitely
 * instead of drifting into the wrong tab as hardcoded absolute dates elapse.
 */
function demoMeetingTimes(offsetDays: number, hour: number, minute: number, durationMinutes: number): { startTime: string; endTime: string } {
  const start = new Date();
  start.setUTCDate(start.getUTCDate() + offsetDays);
  start.setUTCHours(hour, minute, 0, 0);
  const end = new Date(start.getTime() + durationMinutes * 60_000);
  return { startTime: start.toISOString(), endTime: end.toISOString() };
}

/** Demo past meetings (15 records) spanning board/marketing/technical/other types across public, private-invited, and private-hidden (rollup) states. */
export const DEMO_PAST_MEETINGS: readonly OrgPastMeeting[] = [
  {
    id: 'pm-1',
    title: 'CNCF Governing Board',
    privacy: 'private',
    type: 'board',
    recurrenceLabel: 'Every week on Thu',
    ...demoMeetingTimes(-6, 17, 0, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'CNCF',
    agenda: 'Q2 financial review. Project graduation vote. Open source strategy alignment.',
    resources: ['Q2 Financial Summary.pdf', 'Project Graduation Proposal.pdf'],
    attendanceTally: { attended: 10, missed: 2, excused: 1 },
    artifact: {
      recordingUrl: 'https://lfx.dev/recordings/demo-cncf-board-jun26',
      transcriptUrl: 'https://lfx.dev/transcripts/demo-cncf-board-jun26',
      aiSummaryId: 'ai-sum-pm-1',
    },
    minutesUploaded: true,
    orgPastInvitees: [
      { name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, attendanceStatus: 'attended' },
      { name: 'Marcus Williams', title: 'CTO', avatarUrl: null, attendanceStatus: 'attended' },
      { name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, attendanceStatus: 'excused' },
    ],
  },
  {
    id: 'pm-2',
    title: 'Kubernetes SIG Docs',
    privacy: 'public',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Tue',
    ...demoMeetingTimes(-22, 16, 0, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Kubernetes',
    agenda: 'Documentation sprint planning. Review PR backlog. Localization status updates.',
    resources: ['Docs Sprint Board.pdf'],
    attendanceTally: { attended: 16, missed: 5, excused: 2 },
    artifact: {
      recordingUrl: null,
      transcriptUrl: 'https://lfx.dev/transcripts/demo-sig-docs-jun10',
      aiSummaryId: null,
    },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Aisha Johnson', title: 'Security Architect', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-3',
    title: 'OpenSSF Board Meeting',
    privacy: 'private',
    type: 'board',
    recurrenceLabel: 'Every month on the 1st Fri',
    ...demoMeetingTimes(-33, 15, 0, 90),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Alpha-Omega initiative review. Membership renewal pipeline. Security scorecard adoption metrics.',
    resources: [],
    attendanceTally: { attended: 8, missed: 3, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [
      { name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, attendanceStatus: 'attended' },
      { name: 'Marcus Williams', title: 'CTO', avatarUrl: null, attendanceStatus: 'missed' },
    ],
  },
  {
    id: 'pm-4',
    title: 'containerd Maintainers Sync',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Wed',
    ...demoMeetingTimes(-3, 14, 0, 45),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'containerd',
    agenda: 'Release branch triage. CVE backlog review.',
    resources: [],
    attendanceTally: { attended: 5, missed: 1, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: 'https://lfx.dev/transcripts/demo-containerd-sync', aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'David Kim', title: 'Staff Engineer', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-5',
    title: 'Envoy Proxy TSC',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every week on Mon',
    ...demoMeetingTimes(-9, 16, 30, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Envoy',
    agenda: 'xDS API versioning. Extension proposal review.',
    resources: ['TSC Notes.pdf'],
    attendanceTally: { attended: 8, missed: 1, excused: 1 },
    artifact: {
      recordingUrl: 'https://lfx.dev/recordings/demo-envoy-tsc',
      transcriptUrl: 'https://lfx.dev/transcripts/demo-envoy-tsc',
      aiSummaryId: 'ai-sum-pm-5',
    },
    minutesUploaded: true,
    orgPastInvitees: [
      { name: 'Aisha Johnson', title: 'Security Architect', avatarUrl: null, attendanceStatus: 'attended' },
      { name: 'Elena Rodriguez', title: 'Staff SWE', avatarUrl: null, attendanceStatus: 'excused' },
    ],
  },
  {
    id: 'pm-6',
    title: 'CNCF Marketing Committee',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: 'Every month on the 2nd Tue',
    ...demoMeetingTimes(-12, 15, 0, 45),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'CNCF',
    agenda: 'KubeCon sponsor recap. Blog content calendar.',
    resources: [],
    attendanceTally: { attended: 4, missed: 2, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-7',
    title: 'OpenSSF Marketing & Comms',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: null,
    ...demoMeetingTimes(-15, 13, 0, 30),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Scorecard adoption case study. Press outreach plan.',
    resources: [],
    attendanceTally: { attended: 3, missed: 0, excused: 1 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Marcus Williams', title: 'CTO', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-8',
    title: 'CNCF Ambassador Sync',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every month on the 1st Wed',
    ...demoMeetingTimes(-18, 17, 30, 30),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Kubernetes',
    agenda: 'Ambassador onboarding cohort. Regional meetup roundup.',
    resources: [],
    attendanceTally: { attended: 10, missed: 2, excused: 1 },
    artifact: { recordingUrl: 'https://lfx.dev/recordings/demo-cncf-ambassador', transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-9',
    title: 'LF Networking Board Meeting',
    privacy: 'public',
    type: 'board',
    recurrenceLabel: 'Every quarter',
    ...demoMeetingTimes(-25, 16, 0, 90),
    foundation: 'LF Networking',
    orgName: 'CoreOS',
    project: 'ONAP',
    agenda: 'Annual budget approval. New member ratification.',
    resources: ['LFN Board Minutes.pdf'],
    attendanceTally: { attended: 12, missed: 1, excused: 0 },
    artifact: {
      recordingUrl: 'https://lfx.dev/recordings/demo-lfn-board',
      transcriptUrl: 'https://lfx.dev/transcripts/demo-lfn-board',
      aiSummaryId: 'ai-sum-pm-9',
    },
    minutesUploaded: true,
    orgPastInvitees: [{ name: 'Marcus Williams', title: 'CTO', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-10',
    title: 'Hyperledger Marketing Committee',
    privacy: 'public',
    type: 'marketing',
    recurrenceLabel: 'Every 2 weeks on Thu',
    ...demoMeetingTimes(-28, 14, 0, 45),
    foundation: 'Hyperledger Foundation',
    orgName: 'CoreOS',
    project: 'Besu',
    agenda: 'Case study pipeline. Conference speaking slots.',
    resources: [],
    attendanceTally: { attended: 5, missed: 1, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: 'https://lfx.dev/transcripts/demo-hyperledger-marketing', aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Nina Volkov', title: 'Product Marketing Lead', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-11',
    title: 'Hyperledger Besu TSC',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Fri',
    ...demoMeetingTimes(-40, 16, 0, 60),
    foundation: 'Hyperledger Foundation',
    orgName: 'CoreOS',
    project: 'Besu',
    agenda: 'Mainnet sync performance. EVM upgrade compatibility.',
    resources: [],
    attendanceTally: { attended: 4, missed: 0, excused: 1 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'David Kim', title: 'Staff Engineer', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-12',
    title: 'LF Energy Community Call',
    privacy: 'public',
    type: 'other',
    recurrenceLabel: 'Every month on the 3rd Thu',
    ...demoMeetingTimes(-50, 15, 30, 60),
    foundation: 'LF Energy',
    orgName: 'CoreOS',
    project: 'OperatorFabric',
    agenda: 'Grid interoperability demo. New contributor intros.',
    resources: [],
    attendanceTally: { attended: 9, missed: 3, excused: 0 },
    artifact: { recordingUrl: 'https://lfx.dev/recordings/demo-lfenergy-community', transcriptUrl: null, aiSummaryId: 'ai-sum-pm-12' },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'James Patel', title: 'Solutions Architect', avatarUrl: null, attendanceStatus: 'missed' }],
  },
  {
    id: 'pm-14',
    title: 'LF AI & Data Marketing Working Group',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: null,
    ...demoMeetingTimes(-60, 11, 0, 30),
    foundation: 'LF AI & Data',
    orgName: 'CoreOS',
    project: 'Milvus',
    agenda: 'Milvus community showcase. Data+AI summit recap.',
    resources: [],
    attendanceTally: { attended: 3, missed: 0, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'Elena Rodriguez', title: 'Staff SWE', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-17',
    title: 'OpenSSF Alpha-Omega Steering',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every month on the 4th Mon',
    ...demoMeetingTimes(-75, 12, 0, 60),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Grant allocation review. Critical project prioritization.',
    resources: ['Alpha-Omega Report.pdf'],
    attendanceTally: { attended: 5, missed: 0, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: 'https://lfx.dev/transcripts/demo-alpha-omega', aiSummaryId: null },
    minutesUploaded: true,
    orgPastInvitees: [{ name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, attendanceStatus: 'attended' }],
  },
  {
    id: 'pm-20',
    title: 'LF Edge EdgeX Foundry Planning',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every 2 weeks on Tue',
    ...demoMeetingTimes(-80, 9, 30, 45),
    foundation: 'LF Edge',
    orgName: 'CoreOS',
    project: 'EdgeX Foundry',
    agenda: 'Device service roadmap. Release train scheduling.',
    resources: [],
    attendanceTally: { attended: 4, missed: 1, excused: 0 },
    artifact: { recordingUrl: null, transcriptUrl: null, aiSummaryId: null },
    minutesUploaded: false,
    orgPastInvitees: [{ name: 'James Patel', title: 'Solutions Architect', avatarUrl: null, attendanceStatus: 'attended' }],
  },
];

/** Demo upcoming meetings (15 records) spanning board/marketing/technical/other types across public, private-invited, and private-hidden (rollup) states, used until real org-scoped data loads (or when a fetch returns none). */
export const DEMO_UPCOMING_MEETINGS: readonly OrgMeeting[] = [
  {
    id: 'um-1',
    title: 'CNCF Governing Board',
    privacy: 'private',
    type: 'board',
    recurrenceLabel: 'Every week on Thu',
    ...demoMeetingTimes(4, 17, 0, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'CNCF',
    agenda: 'Q3 budget planning. Board seat nominations. Open source strategy alignment.',
    resources: ['Q3 Budget Draft.pdf'],
    rsvpTally: { yes: 8, maybe: 1, no: 0, noResponse: 2 },
    orgInvitees: [
      { name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, rsvpStatus: 'yes' },
      { name: 'Marcus Williams', title: 'CTO', avatarUrl: null, rsvpStatus: 'yes' },
      { name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, rsvpStatus: 'maybe' },
    ],
    guestCount: 2,
    joinUrl: 'https://lfx.dev/join/demo-cncf-board',
    statusFlags: { recording: true, transcripts: true, aiSummary: false },
  },
  {
    id: 'um-2',
    title: 'Kubernetes SIG Docs',
    privacy: 'public',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Tue',
    ...demoMeetingTimes(10, 16, 0, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Kubernetes',
    agenda: 'Documentation sprint retro. Style guide updates. Localization status.',
    resources: ['Docs Sprint Board.pdf'],
    rsvpTally: { yes: 12, maybe: 3, no: 1, noResponse: 4 },
    orgInvitees: [{ name: 'Aisha Johnson', title: 'Security Architect', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 5,
    joinUrl: 'https://lfx.dev/join/demo-sig-docs',
    statusFlags: { recording: false, transcripts: true, aiSummary: true },
  },
  {
    id: 'um-3',
    title: 'OpenSSF Board Meeting',
    privacy: 'private',
    type: 'board',
    recurrenceLabel: 'Every month on the 1st Fri',
    ...demoMeetingTimes(18, 15, 0, 90),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Alpha-Omega initiative review. Membership renewal pipeline. Security scorecard adoption metrics.',
    resources: [],
    rsvpTally: { yes: 6, maybe: 0, no: 0, noResponse: 3 },
    orgInvitees: [
      { name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, rsvpStatus: 'yes' },
      { name: 'Marcus Williams', title: 'CTO', avatarUrl: null, rsvpStatus: null },
    ],
    guestCount: 1,
    joinUrl: 'https://lfx.dev/join/demo-openssf-board',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-4',
    title: 'containerd Maintainers Sync',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Wed',
    ...demoMeetingTimes(6, 14, 0, 45),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'containerd',
    agenda: 'Release branch triage. CVE backlog review. Runtime shim test plan.',
    resources: [],
    rsvpTally: { yes: 5, maybe: 1, no: 0, noResponse: 1 },
    orgInvitees: [{ name: 'David Kim', title: 'Staff Engineer', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 1,
    joinUrl: 'https://lfx.dev/join/demo-containerd-sync',
    statusFlags: { recording: false, transcripts: true, aiSummary: false },
  },
  {
    id: 'um-5',
    title: 'Envoy Proxy TSC',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every week on Mon',
    ...demoMeetingTimes(8, 16, 30, 60),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Envoy',
    agenda: 'xDS API versioning. Extension proposal review. Release cadence discussion.',
    resources: ['TSC Charter.pdf'],
    rsvpTally: { yes: 7, maybe: 2, no: 0, noResponse: 1 },
    orgInvitees: [
      { name: 'Aisha Johnson', title: 'Security Architect', avatarUrl: null, rsvpStatus: 'yes' },
      { name: 'Elena Rodriguez', title: 'Staff SWE', avatarUrl: null, rsvpStatus: 'maybe' },
    ],
    guestCount: 3,
    joinUrl: 'https://lfx.dev/join/demo-envoy-tsc',
    statusFlags: { recording: true, transcripts: true, aiSummary: true },
  },
  {
    id: 'um-6',
    title: 'CNCF Marketing Committee',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: 'Every month on the 2nd Tue',
    ...demoMeetingTimes(12, 15, 0, 45),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'CNCF',
    agenda: 'KubeCon sponsor recap. Blog content calendar. Social campaign metrics.',
    resources: [],
    rsvpTally: { yes: 4, maybe: 0, no: 1, noResponse: 2 },
    orgInvitees: [{ name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 2,
    joinUrl: 'https://lfx.dev/join/demo-cncf-marketing',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-7',
    title: 'OpenSSF Marketing & Comms',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: null,
    ...demoMeetingTimes(15, 13, 0, 30),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Scorecard adoption case study. Press outreach plan.',
    resources: [],
    rsvpTally: { yes: 3, maybe: 1, no: 0, noResponse: 0 },
    orgInvitees: [{ name: 'Marcus Williams', title: 'CTO', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 0,
    joinUrl: 'https://lfx.dev/join/demo-openssf-comms',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-8',
    title: 'CNCF Ambassador Sync',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every month on the 1st Wed',
    ...demoMeetingTimes(20, 17, 30, 30),
    foundation: 'Cloud Native Computing Foundation',
    orgName: 'CoreOS',
    project: 'Kubernetes',
    agenda: 'Ambassador onboarding cohort. Regional meetup roundup.',
    resources: [],
    rsvpTally: { yes: 9, maybe: 2, no: 0, noResponse: 3 },
    orgInvitees: [{ name: 'Sarah Chen', title: 'VP Engineering', avatarUrl: null, rsvpStatus: 'maybe' }],
    guestCount: 4,
    joinUrl: 'https://lfx.dev/join/demo-cncf-ambassador',
    statusFlags: { recording: true, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-9',
    title: 'LF Networking Board Meeting',
    privacy: 'public',
    type: 'board',
    recurrenceLabel: 'Every quarter',
    ...demoMeetingTimes(25, 16, 0, 90),
    foundation: 'LF Networking',
    orgName: 'CoreOS',
    project: 'ONAP',
    agenda: 'Annual budget approval. New member ratification. Roadmap alignment across LFN projects.',
    resources: ['LFN Board Packet.pdf'],
    rsvpTally: { yes: 11, maybe: 1, no: 0, noResponse: 2 },
    orgInvitees: [{ name: 'Marcus Williams', title: 'CTO', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 5,
    joinUrl: 'https://lfx.dev/join/demo-lfn-board',
    statusFlags: { recording: true, transcripts: true, aiSummary: true },
  },
  {
    id: 'um-10',
    title: 'Hyperledger Marketing Committee',
    privacy: 'public',
    type: 'marketing',
    recurrenceLabel: 'Every 2 weeks on Thu',
    ...demoMeetingTimes(30, 14, 0, 45),
    foundation: 'Hyperledger Foundation',
    orgName: 'CoreOS',
    project: 'Besu',
    agenda: 'Case study pipeline. Conference speaking slots. Newsletter refresh.',
    resources: [],
    rsvpTally: { yes: 6, maybe: 0, no: 0, noResponse: 1 },
    orgInvitees: [{ name: 'Nina Volkov', title: 'Product Marketing Lead', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 2,
    joinUrl: 'https://lfx.dev/join/demo-hyperledger-marketing',
    statusFlags: { recording: false, transcripts: true, aiSummary: false },
  },
  {
    id: 'um-11',
    title: 'LF Energy Community Call',
    privacy: 'public',
    type: 'other',
    recurrenceLabel: 'Every month on the 3rd Thu',
    ...demoMeetingTimes(40, 15, 30, 60),
    foundation: 'LF Energy',
    orgName: 'CoreOS',
    project: 'OperatorFabric',
    agenda: 'Grid interoperability demo. New contributor intros. Q&A.',
    resources: [],
    rsvpTally: { yes: 8, maybe: 3, no: 1, noResponse: 2 },
    orgInvitees: [{ name: 'James Patel', title: 'Solutions Architect', avatarUrl: null, rsvpStatus: 'no' }],
    guestCount: 6,
    joinUrl: 'https://lfx.dev/join/demo-lfenergy-community',
    statusFlags: { recording: true, transcripts: false, aiSummary: true },
  },
  {
    id: 'um-12',
    title: 'OpenSSF Alpha-Omega Steering',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every month on the 4th Mon',
    ...demoMeetingTimes(50, 12, 0, 60),
    foundation: 'Open Source Security Foundation',
    orgName: 'CoreOS',
    project: 'OpenSSF',
    agenda: 'Grant allocation review. Critical project prioritization.',
    resources: ['Alpha-Omega Q3 Report.pdf'],
    rsvpTally: { yes: 5, maybe: 0, no: 0, noResponse: 1 },
    orgInvitees: [{ name: 'Priya Sharma', title: 'Director of Open Source', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 1,
    joinUrl: 'https://lfx.dev/join/demo-alpha-omega',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-15',
    title: 'Hyperledger Besu TSC',
    privacy: 'private',
    type: 'technical',
    recurrenceLabel: 'Every 2 weeks on Fri',
    ...demoMeetingTimes(60, 16, 0, 60),
    foundation: 'Hyperledger Foundation',
    orgName: 'CoreOS',
    project: 'Besu',
    agenda: 'Mainnet sync performance. EVM upgrade compatibility.',
    resources: [],
    rsvpTally: { yes: 4, maybe: 1, no: 0, noResponse: 2 },
    orgInvitees: [{ name: 'David Kim', title: 'Staff Engineer', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 0,
    joinUrl: 'https://lfx.dev/join/demo-besu-tsc',
    statusFlags: { recording: false, transcripts: true, aiSummary: false },
  },
  {
    id: 'um-18',
    title: 'LF AI & Data Marketing Working Group',
    privacy: 'private',
    type: 'marketing',
    recurrenceLabel: null,
    ...demoMeetingTimes(70, 11, 0, 30),
    foundation: 'LF AI & Data',
    orgName: 'CoreOS',
    project: 'Milvus',
    agenda: 'Milvus community showcase. Data+AI summit recap.',
    resources: [],
    rsvpTally: { yes: 3, maybe: 0, no: 0, noResponse: 0 },
    orgInvitees: [{ name: 'Elena Rodriguez', title: 'Staff SWE', avatarUrl: null, rsvpStatus: 'yes' }],
    guestCount: 1,
    joinUrl: 'https://lfx.dev/join/demo-lfai-marketing',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
  {
    id: 'um-21',
    title: 'LF Edge EdgeX Foundry Planning',
    privacy: 'private',
    type: 'other',
    recurrenceLabel: 'Every 2 weeks on Tue',
    ...demoMeetingTimes(45, 9, 30, 45),
    foundation: 'LF Edge',
    orgName: 'CoreOS',
    project: 'EdgeX Foundry',
    agenda: 'Device service roadmap. Release train scheduling.',
    resources: [],
    rsvpTally: { yes: 4, maybe: 1, no: 0, noResponse: 1 },
    orgInvitees: [{ name: 'James Patel', title: 'Solutions Architect', avatarUrl: null, rsvpStatus: 'maybe' }],
    guestCount: 0,
    joinUrl: 'https://lfx.dev/join/demo-edgex-planning',
    statusFlags: { recording: false, transcripts: false, aiSummary: false },
  },
];
