// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { isPlatformBrowser } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { inject, Injectable, PLATFORM_ID, Signal, signal } from '@angular/core';
import { NewsletterBlockManifestEntry, NewsletterTemplateManifest } from '@lfx-one/shared/interfaces';
import { catchError, finalize, Observable, of, shareReplay, take, tap } from 'rxjs';

/**
 * Loads the Phase-1 newsletter block manifest — the palette of block types and
 * their field schemas — from the build-time asset bundled at
 * `/assets/newsletter-block-manifest.json` (generated by
 * `scripts/build-newsletter-manifest.mjs` from the declarative template repo).
 *
 * The manifest is static (changes only when templates are re-pulled at build
 * time), so the HTTP request is cached with `shareReplay`. The fetch is
 * browser-only: SSR would have no use for the editor palette and the asset path
 * is relative, so we guard the request behind `isPlatformBrowser` and expose the
 * loaded manifest as a signal for component consumption.
 */
@Injectable({
  providedIn: 'root',
})
export class NewsletterManifestService {
  private readonly http = inject(HttpClient);
  private readonly platformId = inject(PLATFORM_ID);

  private readonly manifestSignal = signal<NewsletterTemplateManifest | null>(null);
  private readonly loadingSignal = signal<boolean>(false);
  private readonly errorSignal = signal<boolean>(false);

  // Cached request shared across subscribers; populated on first load().
  private manifest$: Observable<NewsletterTemplateManifest | null> | null = null;

  /** Read-only view of the loaded manifest (null until loaded / on failure). */
  public get manifest(): Signal<NewsletterTemplateManifest | null> {
    return this.manifestSignal.asReadonly();
  }

  /** True while the manifest request is in flight. */
  public get loading(): Signal<boolean> {
    return this.loadingSignal.asReadonly();
  }

  /** True when the most recent load attempt failed. */
  public get error(): Signal<boolean> {
    return this.errorSignal.asReadonly();
  }

  /**
   * Fetch and cache the manifest. Safe to call repeatedly — the underlying
   * request is shared. No-ops on the server (returns an empty manifest stream)
   * so SSR never reaches for the relative asset URL.
   */
  public load(): Observable<NewsletterTemplateManifest | null> {
    if (!isPlatformBrowser(this.platformId)) {
      return of(null);
    }
    if (this.manifest$) {
      return this.manifest$;
    }

    this.loadingSignal.set(true);
    this.errorSignal.set(false);

    this.manifest$ = this.http.get<NewsletterTemplateManifest>('/assets/newsletter-block-manifest.json').pipe(
      tap((manifest) => this.manifestSignal.set(manifest)),
      catchError(() => {
        this.errorSignal.set(true);
        // Reset the cache so a later retry can re-issue the request.
        this.manifest$ = null;
        return of(null);
      }),
      finalize(() => this.loadingSignal.set(false)),
      shareReplay({ bufferSize: 1, refCount: false })
    );

    return this.manifest$;
  }

  /** Look up a single block manifest entry by its `block_type`. */
  public getBlock(blockType: string): NewsletterBlockManifestEntry | undefined {
    return this.manifestSignal()?.blocks.find((block) => block.block_type === blockType);
  }

  /** Convenience: kick off the load and take a single emission. */
  public ensureLoaded(): Observable<NewsletterTemplateManifest | null> {
    return this.load().pipe(take(1));
  }
}
