// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type { OrgGroupDetail } from '@lfx-one/shared/interfaces';

const d = (iso: string): Date => new Date(iso);

const GENERIC_DETAIL: OrgGroupDetail = {
  id: 'generic',
  name: 'Group',
  description: '',
  type: 'Other',
  foundation: 'Linux Foundation',
  visibility: 'PUBLIC',
  votingEnabled: false,
  memberCount: 10,
  hasMailingList: false,
  hasChatChannel: false,
  updatedAt: d('2026-05-01T00:00:00Z'),
  parentProject: 'Linux Foundation',
  parentProjectId: 'lf',
  createdAt: d('2024-01-15T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 4,
  activeVoteCount: 0,
  openSurveyCount: 0,
  inviteOnly: false,
  chairs: [{ id: 'c1', name: 'Jane Smith', initials: 'JS', avatarColor: 'bg-blue-500' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Monthly Meeting',
      monthAbbr: 'JUL',
      day: 14,
      dayOfWeek: 'Mon',
      time: '2:00 PM',
      durationMin: 60,
      projectName: 'Linux Foundation',
      meetingType: 'Regular',
      hasReminder: false,
      hasAiSummary: false,
      description: 'Monthly sync covering project updates, roadmap items, and open action items.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Monthly Meeting',
      monthAbbr: 'JUN',
      day: 16,
      dayOfWeek: 'Mon',
      time: '2:00 PM',
      durationMin: 60,
      projectName: 'Linux Foundation',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Monthly sync covering project updates, roadmap items, and open action items.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
};

const LF_KERNEL_BOARD: OrgGroupDetail = {
  id: 'lf-kernel-board',
  name: 'Linux Kernel Maintainers Board',
  description: 'Governing board for the Linux Kernel project maintainers.',
  type: 'Board',
  foundation: 'Linux Foundation',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 12,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-04-07T00:00:00Z'),
  parentProject: 'Linux Kernel',
  parentProjectId: 'linux-kernel',
  createdAt: d('2020-03-01T00:00:00Z'),
  organizationCount: 8,
  meetingCount: 24,
  activeVoteCount: 1,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [
    { id: 'c1', name: 'Linus Torvalds', initials: 'LT', avatarColor: 'bg-violet-500' },
    { id: 'c2', name: 'Greg Kroah-Hartman', initials: 'GK', avatarColor: 'bg-blue-500' },
  ],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Linux Kernel Board Meeting',
      monthAbbr: 'JUL',
      day: 8,
      dayOfWeek: 'Tue',
      time: '3:00 PM',
      durationMin: 60,
      projectName: 'Linux Kernel',
      meetingType: 'Board',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Quarterly board meeting to review kernel governance, security patches, and maintainer updates.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Linux Kernel Board Meeting',
      monthAbbr: 'JUN',
      day: 10,
      dayOfWeek: 'Tue',
      time: '3:00 PM',
      durationMin: 60,
      projectName: 'Linux Kernel',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Quarterly board meeting to review kernel governance, security patches, and maintainer updates.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  mailingListName: 'kernel-board@lists.linuxfoundation.org',
  mailingListSubscribers: 12,
  mailingListIsPrivate: true,
};

const LFAI_GOVERNING_BOARD: OrgGroupDetail = {
  id: 'lfai-governing-board',
  name: 'LF AI & Data Governing Board',
  description: 'Sets strategic direction and oversees membership, budget, and governance for LF AI & Data Foundation projects.',
  type: 'Board',
  foundation: 'LF AI & Data',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 9,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-06-19T00:00:00Z'),
  parentProject: 'LF AI & Data Foundation',
  parentProjectId: 'lfai-data',
  createdAt: d('2019-09-10T00:00:00Z'),
  organizationCount: 7,
  meetingCount: 18,
  activeVoteCount: 0,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [{ id: 'c1', name: 'Ibrahim Haddad', initials: 'IH', avatarColor: 'bg-emerald-500' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'LF AI & Data Board Meeting',
      monthAbbr: 'JUL',
      day: 15,
      dayOfWeek: 'Tue',
      time: '10:00 AM',
      durationMin: 90,
      projectName: 'LF AI & Data Foundation',
      meetingType: 'Board',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Board meeting covering strategic initiatives, budget review, and member updates for LF AI & Data.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'LF AI & Data Board Meeting',
      monthAbbr: 'JUN',
      day: 17,
      dayOfWeek: 'Tue',
      time: '10:00 AM',
      durationMin: 90,
      projectName: 'LF AI & Data Foundation',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Board meeting covering strategic initiatives, budget review, and member updates for LF AI & Data.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  mailingListName: 'lfai-governing-board@lists.lfaidata.foundation',
  mailingListSubscribers: 9,
  mailingListIsPrivate: true,
};

const K8S_STEERING: OrgGroupDetail = {
  id: 'k8s-steering',
  name: 'Kubernetes Steering Committee',
  description: '',
  type: 'Board',
  foundation: 'CNCF',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 7,
  hasMailingList: true,
  hasChatChannel: true,
  updatedAt: d('2026-06-09T00:00:00Z'),
  parentProject: 'Kubernetes',
  parentProjectId: 'kubernetes',
  createdAt: d('2017-08-16T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 32,
  activeVoteCount: 2,
  openSurveyCount: 1,
  inviteOnly: true,
  chairs: [
    { id: 'c1', name: 'Bob Killen', initials: 'BK', avatarColor: 'bg-blue-600' },
    { id: 'c2', name: 'Christoph Blecker', initials: 'CB', avatarColor: 'bg-rose-500' },
  ],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Kubernetes Steering Meeting',
      monthAbbr: 'JUL',
      day: 10,
      dayOfWeek: 'Thu',
      time: '9:00 AM',
      durationMin: 60,
      projectName: 'Kubernetes',
      meetingType: 'Steering',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Biweekly steering committee sync on project governance, contributor experience, and community health.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Kubernetes Steering Meeting',
      monthAbbr: 'JUN',
      day: 26,
      dayOfWeek: 'Thu',
      time: '9:00 AM',
      durationMin: 60,
      projectName: 'Kubernetes',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Biweekly steering committee sync on project governance, contributor experience, and community health.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  mailingListName: 'steering@kubernetes.io',
  mailingListSubscribers: 120,
  mailingListIsPrivate: false,
};

const PYTORCH_BOARD: OrgGroupDetail = {
  id: 'pytorch-board',
  name: 'PyTorch Governing Board',
  description: '',
  type: 'Board',
  foundation: 'LF AI & Data',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 6,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-04-07T00:00:00Z'),
  parentProject: 'PyTorch',
  parentProjectId: 'pytorch',
  createdAt: d('2022-09-12T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 12,
  activeVoteCount: 0,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [{ id: 'c1', name: 'David Nalley', initials: 'DN', avatarColor: 'bg-amber-500' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'PyTorch Governing Board Meeting',
      monthAbbr: 'DEC',
      day: 15,
      dayOfWeek: 'Mon',
      time: '4:00 PM',
      durationMin: 45,
      projectName: 'PyTorch',
      meetingType: 'Other',
      hasReminder: false,
      hasAiSummary: false,
      description: 'Governing board session to discuss PyTorch roadmap, working group reports, and community initiatives.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'PyTorch Governing Board Meeting',
      monthAbbr: 'JUN',
      day: 17,
      dayOfWeek: 'Wed',
      time: '4:00 PM',
      durationMin: 60,
      projectName: 'PyTorch',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Governing board session to discuss PyTorch roadmap, working group reports, and community initiatives.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  mailingListName: 'pytorch-board@lists.lfaidata.foundation',
  mailingListSubscribers: 6,
  mailingListIsPrivate: true,
};

export const ORG_GROUP_DETAIL_DEMO_MAP: Readonly<Record<string, OrgGroupDetail>> = {
  'lf-kernel-board': LF_KERNEL_BOARD,
  'lfai-governing-board': LFAI_GOVERNING_BOARD,
  'k8s-steering': K8S_STEERING,
  'pytorch-board': PYTORCH_BOARD,
} as const;

export function getGroupDetailDemo(id: string): OrgGroupDetail {
  return ORG_GROUP_DETAIL_DEMO_MAP[id] ?? { ...GENERIC_DETAIL, id };
}
