// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type { OrgGroup, OrgGroupsStats } from '@lfx-one/shared/interfaces';

const daysAgo = (n: number): Date => new Date(new Date('2026-06-26T00:00:00Z').getTime() - n * 24 * 60 * 60 * 1000);

export const ORG_GROUPS_DEMO_DATA: readonly OrgGroup[] = [
  {
    id: 'agentic-ai-governing-board',
    name: 'Agentic AI Foundation | Governing Board',
    description: '',
    type: 'Board',
    foundation: 'Agentic AI Foundation',
    visibility: 'PRIVATE',
    votingEnabled: true,
    memberCount: 32,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(125),
  },
  {
    id: 'cncf-toc',
    name: 'CNCF Technical Oversight Committee',
    description: '',
    type: 'TAC',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 23,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(125),
  },
  {
    id: 'lf-kernel-board',
    name: 'Linux Kernel Maintainers Board',
    description: '',
    type: 'Board',
    foundation: 'Linux Foundation',
    visibility: 'PRIVATE',
    votingEnabled: true,
    memberCount: 12,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(110),
  },
  {
    id: 'openssf-security-wg',
    name: 'OpenSSF Security Working Group',
    description: '',
    type: 'Working Group',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 34,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(17),
  },
  {
    id: 'k8s-sig-auth',
    name: 'Kubernetes SIG-Auth',
    description: '',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 18,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(5),
  },
  {
    id: 'lfai-governing-board',
    name: 'LF AI & Data Governing Board',
    description: 'Sets strategic direction and oversees membership, budget, and governance for LF AI & Data Foundation projects.',
    type: 'Board',
    foundation: 'LF AI & Data',
    visibility: 'PRIVATE',
    votingEnabled: true,
    memberCount: 9,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(7),
  },
  {
    id: 'openssf-tac',
    name: 'OpenSSF Technical Advisory Council',
    description: '',
    type: 'TAC',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 11,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(21),
  },
  {
    id: 'cncf-marketing',
    name: 'CNCF Marketing Committee',
    description: '',
    type: 'Marketing Committee',
    foundation: 'CNCF',
    visibility: 'PRIVATE',
    votingEnabled: false,
    memberCount: 7,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(82),
  },
  {
    id: 'k8s-steering',
    name: 'Kubernetes Steering Committee',
    description: '',
    type: 'Board',
    foundation: 'CNCF',
    visibility: 'PRIVATE',
    votingEnabled: true,
    memberCount: 7,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(17),
  },
  {
    id: 'lfn-technical-advisory',
    name: 'LF Networking Technical Advisory Board',
    description: '',
    type: 'TAC',
    foundation: 'Linux Foundation',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 15,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(3),
  },
  {
    id: 'pytorch-board',
    name: 'PyTorch Governing Board',
    description: '',
    type: 'Board',
    foundation: 'LF AI & Data',
    visibility: 'PRIVATE',
    votingEnabled: true,
    memberCount: 6,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(82),
  },
  {
    id: 'cncf-end-user-tac',
    name: 'CNCF End User Technical Advisory Group',
    description: '',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 41,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(11),
  },
  {
    id: 'openssf-best-practices-wg',
    name: 'OpenSSF Best Practices Working Group',
    description: '',
    type: 'Working Group',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 28,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(81),
  },
  {
    id: 'lf-edge-arch',
    name: 'LF Edge Architecture Committee',
    description: '',
    type: 'Other',
    foundation: 'Linux Foundation',
    visibility: 'PRIVATE',
    votingEnabled: false,
    memberCount: 14,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(82),
  },
  {
    id: 'cncf-budget',
    name: 'CNCF Budget Committee',
    description: '',
    type: 'Other',
    foundation: 'CNCF',
    visibility: 'PRIVATE',
    votingEnabled: false,
    memberCount: 5,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(81),
  },
  {
    id: 'k8s-docs-wg',
    name: 'Kubernetes Documentation Working Group',
    description: '',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 45,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(11),
  },
] as const;

export const ORG_GROUPS_DEMO_STATS: OrgGroupsStats = {
  total: ORG_GROUPS_DEMO_DATA.length,
  public: ORG_GROUPS_DEMO_DATA.filter((g) => g.visibility === 'PUBLIC').length,
  votingEnabled: ORG_GROUPS_DEMO_DATA.filter((g) => g.votingEnabled).length,
  boardCount: ORG_GROUPS_DEMO_DATA.filter((g) => g.type === 'Board').length,
  otherCount: ORG_GROUPS_DEMO_DATA.filter((g) => g.type !== 'Board').length,
  foundationCount: new Set(ORG_GROUPS_DEMO_DATA.map((g) => g.foundation)).size,
};
