// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { PollStatus, SurveyStatus } from '@lfx-one/shared/enums';
import type { OrgGroup, OrgGroupDetail } from '@lfx-one/shared/interfaces';
import { deriveDemoViewerIsGroupMember } from '@lfx-one/shared/utils';

import { ORG_GROUPS_DEMO_DATA } from './org-groups-demo.data';

const d = (iso: string): Date => new Date(iso);

const MAILING_LIST_DOMAINS: Readonly<Record<string, string>> = {
  'Linux Foundation': 'lists.linuxfoundation.org',
  CNCF: 'lists.cncf.io',
  'LF AI & Data': 'lists.lfaidata.foundation',
  OpenSSF: 'lists.openssf.org',
  'Agentic AI Foundation': 'lists.agenticaifoundation.org',
};

const slugify = (name: string): string =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');

function buildGenericChannels(listGroup: OrgGroup): Partial<OrgGroupDetail> {
  const slug = slugify(listGroup.name);
  const domain = MAILING_LIST_DOMAINS[listGroup.foundation] ?? MAILING_LIST_DOMAINS['Linux Foundation'];

  return {
    ...(listGroup.hasMailingList && {
      mailingListName: `${slug}@${domain}`,
      mailingListSubscribers: listGroup.memberCount,
      mailingListIsPrivate: listGroup.visibility === 'PRIVATE',
    }),
    ...(listGroup.hasChatChannel && {
      chatChannelUrl: `https://linuxfoundation.slack.com/archives/${slug}`,
    }),
  };
}

const GENERIC_DETAIL: OrgGroupDetail = {
  id: 'generic',
  name: 'Group',
  description: '',
  type: 'Other',
  foundation: 'Linux Foundation',
  visibility: 'PUBLIC',
  votingEnabled: false,
  memberCount: 10,
  hasMailingList: false,
  hasChatChannel: false,
  updatedAt: d('2026-05-01T00:00:00Z'),
  parentProject: 'Linux Foundation',
  parentProjectId: 'lf',
  createdAt: d('2024-01-15T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 4,
  openSurveyCount: 1,
  inviteOnly: false,
  chairs: [{ id: 'c1', name: 'Jane Smith', initials: 'JS', role: 'Chair' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Monthly Meeting',
      monthAbbr: 'JUL',
      day: 14,
      dayOfWeek: 'Tue',
      time: '2:00 PM',
      durationMin: 60,
      projectName: 'Linux Foundation',
      meetingType: 'Regular',
      hasReminder: false,
      hasAiSummary: false,
      description: 'Monthly sync covering project updates, roadmap items, and open action items.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Monthly Meeting',
      monthAbbr: 'JUN',
      day: 16,
      dayOfWeek: 'Tue',
      time: '2:00 PM',
      durationMin: 60,
      projectName: 'Linux Foundation',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Monthly sync covering project updates, roadmap items, and open action items.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  members: [
    { id: 'gm1', name: 'Jane Smith', email: 'jane.smith@example.org', organizationName: 'Example Corp', role: 'Chair', votingStatus: 'Voting Rep' },
    { id: 'gm2', name: 'Alex Johnson', email: 'alex.johnson@example.org', organizationName: 'Acme Inc', role: 'Member', votingStatus: 'Voting Rep' },
  ],
  votes: [
    {
      uid: 'v1',
      name: 'Officer Election',
      description: 'Annual officer election.',
      end_time: '2026-07-25T00:00:00Z',
      status: PollStatus.ACTIVE,
      project_uid: 'lf',
      committee_name: 'Group',
      num_response_received: 4,
      total_voting_request_invitations: 10,
    },
  ],
  surveys: [
    {
      uid: 's1',
      survey_title: 'Member Satisfaction Survey',
      survey_status: SurveyStatus.OPEN,
      survey_cutoff_date: '2026-07-30T00:00:00Z',
      is_nps_survey: true,
      is_project_survey: false,
      committees: [
        {
          committee_id: 'c1',
          committee_uid: 'c1',
          committee_name: 'Group',
          project_id: 'lf',
          project_uid: 'lf',
          project_name: 'Linux Foundation',
          total_recipients: 10,
          total_responses: 4,
          nps_value: 40,
          num_detractors: 1,
          num_passives: 3,
          num_promoters: 6,
        },
      ],
      committee_category: 'Other',
      total_responses: 4,
      total_recipients: 10,
      created_at: '2026-06-01T00:00:00Z',
      last_modified_at: '2026-06-15T00:00:00Z',
      creator_name: 'Jane Smith',
    },
  ],
  documents: [
    {
      id: 'doc1',
      name: 'Meeting Minutes - June 2026.pdf',
      source: 'file',
      foundationName: 'Linux Foundation',
      groupOrMeetingName: 'Group',
      groupOrMeetingUid: 'generic',
      date: '2026-06-16T00:00:00Z',
      fileType: 'pdf',
    },
  ],
};

const LF_KERNEL_BOARD: OrgGroupDetail = {
  id: 'lf-kernel-board',
  name: 'Linux Kernel Maintainers Board',
  description: 'Governing board for the Linux Kernel project maintainers.',
  type: 'Board',
  foundation: 'Linux Foundation',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 12,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-04-07T00:00:00Z'),
  parentProject: 'Linux Kernel',
  parentProjectId: 'linux-kernel',
  createdAt: d('2020-03-01T00:00:00Z'),
  organizationCount: 8,
  meetingCount: 24,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [
    { id: 'c1', name: 'Linus Torvalds', initials: 'LT', role: 'Chair' },
    { id: 'c2', name: 'Greg Kroah-Hartman', initials: 'GK', role: 'Vice Chair' },
  ],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Linux Kernel Board Meeting',
      monthAbbr: 'JUL',
      day: 22,
      dayOfWeek: 'Wed',
      time: '3:00 PM',
      durationMin: 60,
      projectName: 'Linux Kernel',
      meetingType: 'Board',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Quarterly board meeting to review kernel governance, security patches, and maintainer updates.',
      isRecurring: true,
      isPrivate: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Linux Kernel Board Meeting',
      monthAbbr: 'JUN',
      day: 10,
      dayOfWeek: 'Wed',
      time: '3:00 PM',
      durationMin: 60,
      projectName: 'Linux Kernel',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Quarterly board meeting to review kernel governance, security patches, and maintainer updates.',
      isRecurring: true,
      hasRecording: true,
      isPrivate: true,
    },
  ],
  members: [
    {
      id: 'gm1',
      name: 'Linus Torvalds',
      email: 'torvalds@linux-foundation.org',
      organizationName: 'Linux Foundation',
      role: 'Chair',
      votingStatus: 'Voting Rep',
    },
    {
      id: 'gm2',
      name: 'Greg Kroah-Hartman',
      email: 'gregkh@linuxfoundation.org',
      organizationName: 'Linux Foundation',
      role: 'Vice Chair',
      votingStatus: 'Voting Rep',
    },
    { id: 'gm3', name: 'Sasha Levin', email: 'sashal@kernel.org', organizationName: 'Google', role: 'Member', votingStatus: 'Voting Rep' },
  ],
  votes: [
    {
      uid: 'v1',
      name: 'Maintainer Nomination: Stable Tree',
      description: 'Vote on the proposed stable-tree co-maintainer nomination.',
      end_time: '2026-07-20T00:00:00Z',
      status: PollStatus.ACTIVE,
      project_uid: 'linux-kernel',
      committee_name: 'Linux Kernel Maintainers Board',
      num_response_received: 7,
      total_voting_request_invitations: 12,
    },
    {
      uid: 'v2',
      name: 'Q1 Security Policy Update',
      end_time: '2026-03-15T00:00:00Z',
      status: PollStatus.ENDED,
      project_uid: 'linux-kernel',
      committee_name: 'Linux Kernel Maintainers Board',
      num_response_received: 12,
      total_voting_request_invitations: 12,
    },
  ],
  surveys: [],
  documents: [
    {
      id: 'doc1',
      name: 'Kernel Board Charter.pdf',
      source: 'file',
      foundationName: 'Linux Foundation',
      groupOrMeetingName: 'Linux Kernel Maintainers Board',
      groupOrMeetingUid: 'lf-kernel-board',
      date: '2020-03-01T00:00:00Z',
      fileType: 'pdf',
    },
    {
      id: 'doc2',
      name: 'Board Meeting Recording - June 2026',
      source: 'recording',
      foundationName: 'Linux Foundation',
      groupOrMeetingName: 'Linux Kernel Board Meeting',
      groupOrMeetingUid: 'lf-kernel-board',
      date: '2026-06-10T00:00:00Z',
    },
  ],
  mailingListName: 'kernel-board@lists.linuxfoundation.org',
  mailingListSubscribers: 12,
  mailingListIsPrivate: true,
};

const LFAI_GOVERNING_BOARD: OrgGroupDetail = {
  id: 'lfai-governing-board',
  name: 'LF AI & Data Governing Board',
  description: 'Sets strategic direction and oversees membership, budget, and governance for LF AI & Data Foundation projects.',
  type: 'Board',
  foundation: 'LF AI & Data',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 9,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-06-19T00:00:00Z'),
  parentProject: 'LF AI & Data Foundation',
  parentProjectId: 'lfai-data',
  createdAt: d('2019-09-10T00:00:00Z'),
  organizationCount: 7,
  meetingCount: 18,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [{ id: 'c1', name: 'Ibrahim Haddad', initials: 'IH', role: 'Chair' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'LF AI & Data Board Meeting',
      monthAbbr: 'JUL',
      day: 15,
      dayOfWeek: 'Wed',
      time: '10:00 AM',
      durationMin: 90,
      projectName: 'LF AI & Data Foundation',
      meetingType: 'Board',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Board meeting covering strategic initiatives, budget review, and member updates for LF AI & Data.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'LF AI & Data Board Meeting',
      monthAbbr: 'JUN',
      day: 17,
      dayOfWeek: 'Wed',
      time: '10:00 AM',
      durationMin: 90,
      projectName: 'LF AI & Data Foundation',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Board meeting covering strategic initiatives, budget review, and member updates for LF AI & Data.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  members: [
    { id: 'gm1', name: 'Ibrahim Haddad', email: 'ihaddad@lfaidata.foundation', organizationName: 'LF AI & Data', role: 'Chair', votingStatus: 'Voting Rep' },
    { id: 'gm2', name: 'Sherard Griffin', email: 'sgriffin@ibm.com', organizationName: 'IBM', role: 'Member', votingStatus: 'Voting Rep' },
  ],
  votes: [
    {
      uid: 'v1',
      name: '2027 Budget Approval',
      description: 'Approve the proposed 2027 annual budget for LF AI & Data.',
      end_time: '2026-08-01T00:00:00Z',
      status: PollStatus.ACTIVE,
      project_uid: 'lfai-data',
      committee_name: 'LF AI & Data Governing Board',
      num_response_received: 5,
      total_voting_request_invitations: 9,
    },
  ],
  surveys: [
    {
      uid: 's1',
      survey_title: 'Board Member Engagement Survey',
      survey_status: SurveyStatus.CLOSED,
      survey_cutoff_date: '2026-05-01T00:00:00Z',
      is_nps_survey: false,
      is_project_survey: false,
      committees: [
        {
          committee_id: 'c1',
          committee_uid: 'c1',
          committee_name: 'LF AI & Data Governing Board',
          project_id: 'lfai-data',
          project_uid: 'lfai-data',
          project_name: 'LF AI & Data Foundation',
          total_recipients: 9,
          total_responses: 8,
          nps_value: 0,
          num_detractors: 0,
          num_passives: 0,
          num_promoters: 0,
        },
      ],
      committee_category: 'Board',
      total_responses: 8,
      total_recipients: 9,
      created_at: '2026-04-01T00:00:00Z',
      last_modified_at: '2026-05-02T00:00:00Z',
      creator_name: 'Ibrahim Haddad',
    },
  ],
  documents: [],
  mailingListName: 'lfai-governing-board@lists.lfaidata.foundation',
  mailingListSubscribers: 9,
  mailingListIsPrivate: true,
};

const K8S_STEERING: OrgGroupDetail = {
  id: 'k8s-steering',
  name: 'Kubernetes Steering Committee',
  description: '',
  type: 'Board',
  foundation: 'CNCF',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 7,
  hasMailingList: true,
  hasChatChannel: true,
  updatedAt: d('2026-06-09T00:00:00Z'),
  parentProject: 'Kubernetes',
  parentProjectId: 'kubernetes',
  createdAt: d('2017-08-16T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 32,
  openSurveyCount: 1,
  inviteOnly: true,
  chairs: [
    { id: 'c1', name: 'Bob Killen', initials: 'BK', role: 'Chair' },
    { id: 'c2', name: 'Christoph Blecker', initials: 'CB', role: 'Vice Chair' },
  ],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Kubernetes Steering Meeting',
      monthAbbr: 'JUL',
      day: 24,
      dayOfWeek: 'Fri',
      time: '9:00 AM',
      durationMin: 60,
      projectName: 'Kubernetes',
      meetingType: 'Steering',
      hasReminder: true,
      hasAiSummary: false,
      description: 'Biweekly steering committee sync on project governance, contributor experience, and community health.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Kubernetes Steering Meeting',
      monthAbbr: 'JUN',
      day: 26,
      dayOfWeek: 'Fri',
      time: '9:00 AM',
      durationMin: 60,
      projectName: 'Kubernetes',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Biweekly steering committee sync on project governance, contributor experience, and community health.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  members: [
    { id: 'gm1', name: 'Bob Killen', email: 'bob@k8s.io', organizationName: 'Google', role: 'Chair', votingStatus: 'Voting Rep' },
    { id: 'gm2', name: 'Christoph Blecker', email: 'christoph@k8s.io', organizationName: 'Red Hat', role: 'Vice Chair', votingStatus: 'Voting Rep' },
    { id: 'gm3', name: 'Nikhita Raghunath', email: 'nikhita@k8s.io', organizationName: 'Loft Labs', role: 'Member', votingStatus: 'Voting Rep' },
  ],
  votes: [
    {
      uid: 'v1',
      name: 'Steering Committee Election',
      description: 'Annual election for open steering committee seats.',
      end_time: '2026-07-18T00:00:00Z',
      status: PollStatus.ACTIVE,
      project_uid: 'kubernetes',
      committee_name: 'Kubernetes Steering Committee',
      num_response_received: 3,
      total_voting_request_invitations: 7,
    },
  ],
  surveys: [
    {
      uid: 's1',
      survey_title: 'Contributor Experience Survey',
      survey_status: SurveyStatus.OPEN,
      survey_cutoff_date: '2026-08-01T00:00:00Z',
      is_nps_survey: true,
      is_project_survey: true,
      committees: [
        {
          committee_id: 'c1',
          committee_uid: 'c1',
          committee_name: 'Kubernetes Steering Committee',
          project_id: 'kubernetes',
          project_uid: 'kubernetes',
          project_name: 'Kubernetes',
          total_recipients: 500,
          total_responses: 180,
          nps_value: 55,
          num_detractors: 20,
          num_passives: 90,
          num_promoters: 70,
        },
      ],
      committee_category: 'Board',
      total_responses: 180,
      total_recipients: 500,
      created_at: '2026-06-01T00:00:00Z',
      last_modified_at: '2026-06-20T00:00:00Z',
      creator_name: 'Bob Killen',
    },
  ],
  documents: [
    {
      id: 'doc1',
      name: 'Steering Committee Charter.pdf',
      source: 'file',
      foundationName: 'CNCF',
      groupOrMeetingName: 'Kubernetes Steering Committee',
      groupOrMeetingUid: 'k8s-steering',
      date: '2017-08-16T00:00:00Z',
      fileType: 'pdf',
    },
  ],
  mailingListName: 'steering@kubernetes.io',
  mailingListSubscribers: 120,
  mailingListIsPrivate: false,
  chatChannelUrl: 'https://kubernetes.slack.com/archives/C09QZTMFN',
  websiteUrl: 'https://github.com/kubernetes/steering',
};

const CNCF_MARKETING: OrgGroupDetail = {
  id: 'cncf-marketing',
  name: 'CNCF Marketing Committee',
  description: 'Coordinates marketing, events, and community communications across CNCF projects.',
  type: 'Other',
  foundation: 'CNCF',
  visibility: 'PRIVATE',
  votingEnabled: false,
  memberCount: 75,
  hasMailingList: false,
  hasChatChannel: true,
  updatedAt: d('2026-04-03T00:00:00Z'),
  parentProject: 'LF Products',
  parentProjectId: 'lf-products',
  createdAt: d('2026-03-23T00:00:00Z'),
  organizationCount: 22,
  meetingCount: 6,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'Marketing Committee Sync',
      monthAbbr: 'JUL',
      day: 23,
      dayOfWeek: 'Thu',
      time: '11:00 AM',
      durationMin: 30,
      projectName: 'CNCF',
      meetingType: 'Other',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Committee sync on upcoming events, content calendar, and community campaigns.',
      isRecurring: true,
      isPrivate: true,
      hasRecording: true,
      hasTranscripts: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'Marketing Committee Sync',
      monthAbbr: 'JUN',
      day: 11,
      dayOfWeek: 'Thu',
      time: '11:00 AM',
      durationMin: 30,
      projectName: 'CNCF',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Committee sync on upcoming events, content calendar, and community campaigns.',
      isRecurring: true,
      isPrivate: true,
      hasRecording: true,
      hasTranscripts: true,
    },
  ],
  members: [
    { id: 'gm1', name: 'Priya Nair', email: 'priya@cncf.io', organizationName: 'CNCF', role: 'Member', votingStatus: 'Non-Voting' },
    { id: 'gm2', name: 'Marcus Chen', email: 'marcus@cncf.io', organizationName: 'CNCF', role: 'Member', votingStatus: 'Non-Voting' },
  ],
  votes: [],
  surveys: [],
  documents: [
    {
      id: 'doc1',
      name: 'Q3 Content Calendar.xlsx',
      source: 'file',
      foundationName: 'CNCF',
      groupOrMeetingName: 'CNCF Marketing Committee',
      groupOrMeetingUid: 'cncf-marketing',
      date: '2026-06-01T00:00:00Z',
      fileType: 'xlsx',
    },
    {
      id: 'doc2',
      name: 'Committee Sync Transcript - June 2026',
      source: 'transcript',
      foundationName: 'CNCF',
      groupOrMeetingName: 'Marketing Committee Sync',
      groupOrMeetingUid: 'cncf-marketing',
      date: '2026-06-11T00:00:00Z',
    },
  ],
  chatChannelUrl: 'https://linuxfoundation.slack.com/archives/C01GB7D71B9',
  websiteUrl: 'https://www.cncf.io/marketing',
};

const PYTORCH_BOARD: OrgGroupDetail = {
  id: 'pytorch-board',
  name: 'PyTorch Governing Board',
  description: '',
  type: 'Board',
  foundation: 'LF AI & Data',
  visibility: 'PRIVATE',
  votingEnabled: true,
  memberCount: 6,
  hasMailingList: true,
  hasChatChannel: false,
  updatedAt: d('2026-04-07T00:00:00Z'),
  parentProject: 'PyTorch',
  parentProjectId: 'pytorch',
  createdAt: d('2022-09-12T00:00:00Z'),
  organizationCount: 5,
  meetingCount: 12,
  openSurveyCount: 0,
  inviteOnly: true,
  chairs: [{ id: 'c1', name: 'David Nalley', initials: 'DN', role: 'Chair' }],
  nextMeetings: [
    {
      id: 'nm1',
      title: 'PyTorch Governing Board Meeting',
      monthAbbr: 'DEC',
      day: 15,
      dayOfWeek: 'Tue',
      time: '4:00 PM',
      durationMin: 45,
      projectName: 'PyTorch',
      meetingType: 'Other',
      hasReminder: false,
      hasAiSummary: false,
      description: 'Governing board session to discuss PyTorch roadmap, working group reports, and community initiatives.',
      isRecurring: true,
    },
  ],
  pastMeetings: [
    {
      id: 'pm1',
      title: 'PyTorch Governing Board Meeting',
      monthAbbr: 'JUN',
      day: 17,
      dayOfWeek: 'Wed',
      time: '4:00 PM',
      durationMin: 60,
      projectName: 'PyTorch',
      meetingType: 'Meeting',
      hasReminder: false,
      hasAiSummary: true,
      description: 'Governing board session to discuss PyTorch roadmap, working group reports, and community initiatives.',
      isRecurring: true,
      hasRecording: true,
    },
  ],
  members: [
    { id: 'gm1', name: 'David Nalley', email: 'dnalley@lfaidata.foundation', organizationName: 'Linux Foundation', role: 'Chair', votingStatus: 'Voting Rep' },
  ],
  votes: [
    {
      uid: 'v1',
      name: 'Governing Board Seat Nomination',
      end_time: '2026-01-15T00:00:00Z',
      status: PollStatus.ENDED,
      project_uid: 'pytorch',
      committee_name: 'PyTorch Governing Board',
      num_response_received: 6,
      total_voting_request_invitations: 6,
    },
  ],
  surveys: [],
  documents: [],
  mailingListName: 'pytorch-board@lists.lfaidata.foundation',
  mailingListSubscribers: 6,
  mailingListIsPrivate: true,
};

export const ORG_GROUP_DETAIL_DEMO_MAP: Readonly<Record<string, OrgGroupDetail>> = {
  'lf-kernel-board': LF_KERNEL_BOARD,
  'lfai-governing-board': LFAI_GOVERNING_BOARD,
  'k8s-steering': K8S_STEERING,
  'pytorch-board': PYTORCH_BOARD,
  'cncf-marketing': CNCF_MARKETING,
} as const;

/**
 * Returns group detail for the given id, or null if the group doesn't exist or the viewer
 * isn't a member of a private group — mirrors the org-groups list page's privacy split
 * (`splitOrgGroupsByPrivacy`) so a private detail page is never reachable by guessing an id.
 */
export function getGroupDetailDemo(id: string): OrgGroupDetail | null {
  const listGroup = ORG_GROUPS_DEMO_DATA.find((g) => g.id === id);
  if (!listGroup) {
    return null;
  }
  if (listGroup.visibility === 'PRIVATE' && !deriveDemoViewerIsGroupMember(id)) {
    return null;
  }

  const curated = ORG_GROUP_DETAIL_DEMO_MAP[id];
  if (curated) {
    return curated;
  }

  return { ...GENERIC_DETAIL, ...listGroup, id, ...buildGenericChannels(listGroup) };
}
