// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type { OrgGroup, OrgGroupsStats } from '@lfx-one/shared/interfaces';

const now = new Date('2026-06-26T00:00:00Z');

const daysAgo = (n: number): Date => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const ORG_GROUPS_DEMO_DATA: readonly OrgGroup[] = [
  {
    id: 'cncf-toc',
    name: 'CNCF Technical Oversight Committee',
    description: 'Oversees technical direction and governance for all CNCF projects, including sandbox, incubating, and graduated tiers.',
    type: 'TAC',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 23,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(3),
  },
  {
    id: 'lf-kernel-board',
    name: 'Linux Kernel Maintainers Board',
    description: 'Governing board for the Linux kernel maintainer community, coordinating release cycles and escalation procedures.',
    type: 'Board',
    foundation: 'Linux Foundation',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 12,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(8),
  },
  {
    id: 'openssf-security-wg',
    name: 'OpenSSF Security Working Group',
    description: 'Develops best practices and tooling to improve the security posture of open-source software ecosystems.',
    type: 'Working Group',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 34,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(1),
  },
  {
    id: 'k8s-sig-auth',
    name: 'Kubernetes SIG-Auth',
    description: 'Special Interest Group focused on Kubernetes authentication, authorization, and certificate management.',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 18,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(5),
  },
  {
    id: 'lfai-governing-board',
    name: 'LF AI & Data Governing Board',
    description: 'Sets strategic direction and oversees membership, budget, and governance for LF AI & Data Foundation projects.',
    type: 'Board',
    foundation: 'LF AI & Data',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 9,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(14),
  },
  {
    id: 'openssf-tac',
    name: 'OpenSSF Technical Advisory Council',
    description: 'Provides technical guidance and reviews project proposals for the Open Source Security Foundation.',
    type: 'TAC',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 11,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(7),
  },
  {
    id: 'cncf-marketing',
    name: 'CNCF Marketing Committee',
    description: 'Coordinates marketing, events, and communications strategy across the CNCF project portfolio.',
    type: 'Marketing Committee',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 7,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(21),
  },
  {
    id: 'k8s-steering',
    name: 'Kubernetes Steering Committee',
    description: 'Governs the Kubernetes project, sets project values, and manages contributions from the broader Kubernetes community.',
    type: 'Board',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 7,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(10),
  },
  {
    id: 'lfn-technical-advisory',
    name: 'LF Networking Technical Advisory Board',
    description: 'Technical advisory board for LF Networking projects, providing architectural review and cross-project coordination.',
    type: 'TAC',
    foundation: 'Linux Foundation',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 15,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(18),
  },
  {
    id: 'pytorch-board',
    name: 'PyTorch Governing Board',
    description: 'Oversees strategic direction, membership, and long-term health of the PyTorch open-source project.',
    type: 'Board',
    foundation: 'LF AI & Data',
    visibility: 'PUBLIC',
    votingEnabled: true,
    memberCount: 6,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(30),
  },
  {
    id: 'cncf-end-user-tac',
    name: 'CNCF End User Technical Advisory Group',
    description: 'Closed working group gathering end-user perspective on CNCF roadmap priorities and graduation criteria.',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PRIVATE',
    votingEnabled: false,
    memberCount: 41,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(2),
  },
  {
    id: 'openssf-best-practices-wg',
    name: 'OpenSSF Best Practices Working Group',
    description: 'Authors and maintains security best-practice guides, scorecards, and the OpenSSF Best Practices Badge program.',
    type: 'Working Group',
    foundation: 'OpenSSF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 28,
    hasMailingList: true,
    hasChatChannel: true,
    updatedAt: daysAgo(4),
  },
  {
    id: 'lf-edge-arch',
    name: 'LF Edge Architecture Committee',
    description: 'Guides architectural decisions and interoperability standards across LF Edge hosted projects.',
    type: 'Other',
    foundation: 'Linux Foundation',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 14,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(45),
  },
  {
    id: 'cncf-budget',
    name: 'CNCF Budget Committee',
    description: 'Internal committee reviewing annual budget requests and approving expenditures for CNCF initiatives.',
    type: 'Other',
    foundation: 'CNCF',
    visibility: 'PRIVATE',
    votingEnabled: false,
    memberCount: 5,
    hasMailingList: true,
    hasChatChannel: false,
    updatedAt: daysAgo(60),
  },
  {
    id: 'k8s-docs-wg',
    name: 'Kubernetes Documentation Working Group',
    description: 'Maintains Kubernetes official documentation, localization infrastructure, and the contributor docs experience.',
    type: 'Working Group',
    foundation: 'CNCF',
    visibility: 'PUBLIC',
    votingEnabled: false,
    memberCount: 45,
    hasMailingList: false,
    hasChatChannel: true,
    updatedAt: daysAgo(6),
  },
] as const;

export const ORG_GROUPS_DEMO_STATS: OrgGroupsStats = {
  total: ORG_GROUPS_DEMO_DATA.length,
  public: ORG_GROUPS_DEMO_DATA.filter((g) => g.visibility === 'PUBLIC').length,
  votingEnabled: ORG_GROUPS_DEMO_DATA.filter((g) => g.votingEnabled).length,
  boardCount: ORG_GROUPS_DEMO_DATA.filter((g) => g.type === 'Board').length,
  otherCount: ORG_GROUPS_DEMO_DATA.filter((g) => g.type !== 'Board').length,
  foundationCount: new Set(ORG_GROUPS_DEMO_DATA.map((g) => g.foundation)).size,
};
